version: '3'

services:


   db:
     image: 'postgres'
     ports:
     - '5432:5432'
     volumes:
        - mydb:/var/lib/postgres
     environment:
        POSTGRES_DB: mydb
        POSTGRES_USER: mydb_user
        POSTGRES_PASSWORD: password

volumes:
 mydb:
        